### ISSUE TITLE
DEPRECATED: Method `remove` is deprecated

### ISSUE THREAD

**Issue by chvonrohr** [topaxi/ember-bootstrap-datepicker#2]
Seems that a new version of boostrap-datepicker renamed the "remove" function:
```DEPRECATED: Method `remove` is deprecated and will be removed in version 2.0. Use `destroy` instead```

I guess this belongs to 
https://github.com/topaxi/ember-bootstrap-datepicker/blob/master/addon/components/datepicker-support.js#L109
and 
https://github.com/topaxi/ember-bootstrap-datepicker/blob/master/addon/components/datepicker-support.js#L80

**Comment by topaxi** [comment]
Thx, fixed 👍
