### ISSUE TITLE
Handwriting does not bind properly

### ISSUE THREAD

**Issue by huberts** [topaxi/ember-bootstrap-datepicker#3]
I noticed one cannot handwrite the date properly. If you choose a date from the component (by clicking on the calendar) it works great. But then, if you try to modify the date by hand - the value does not bind.
I created a simple example (ember new + ember install ember-bootstrap-datepicker + test case):

[https://github.com/huberts/ember-bootstrap-datepicker-test](https://github.com/huberts/ember-bootstrap-datepicker-test)

The same test seems to work on ember-cli-bootstrap-datepicker (ver. 0.5.6) in my other app.

**Comment by topaxi** [comment]
Thanks for reporting, I will look at this as soon as I found some free time.

**Comment by huberts** [comment]
I've tested the same case with ember-cli-bootstrap-datepicker, and it does not work either. EmberCLI@2.15.0.

**Comment by huberts** [comment]
#4 What do you think of the solution?

**Comment by huberts** [comment]
Can I ping you about this issue once again?

**Comment by topaxi** [comment]
Yes of course, sorry I haven't had time to look into this, trying to take a look tomorrow evening.
