### ISSUE TITLE
Re-select on second click

### ISSUE THREAD

**Issue by huberts** [topaxi/ember-bootstrap-datepicker#7]
Hi!
Since this new version (2.0.3) there occured a regression. If you pick a date, and then try to do it again on the same component, you need to click twice to get data. You can see this on:
[https://github.com/huberts/ember-bootstrap-datepicker-test](https://github.com/huberts/ember-bootstrap-datepicker-test).

**Comment by topaxi** [comment]
Thanks for reporting this, I probably won't have time looking into this this week.
I'll see if I can get some time next week.

**Comment by jbk83** [comment]
I have fixed the issue but I cannot add pull request here. You can see the correction on mine fork: https://github.com/LeCollectionist/ember-bootstrap-datepicker

**Comment by ivorscott** [comment]
If you pick a date, and then try to do it again on the same component, you need to click twice to get data because the first click unfocuses the input field and the second does the update.

**Comment by chvonrohr** [comment]
I guess this was introduced with the ```forceParse``` option.
What was the reason for this option? 
The datepicker seems to update properly when entering the date manually...

This can be solved with setting ```forceParse``` to ```false```.

**Comment by chvonrohr** [comment]
I just experienced, that entering 1.1.2019 does not get parsed to 01.01.2019 without the ```forceParse``` option. Would it be a solution, to execute parsing only on ```datepicker.on(hide)```?
This would solve the issue.
