### ISSUE TITLE
Date-Format Problem since ```forceParse``` update

### ISSUE THREAD

**Issue by chvonrohr** [topaxi/ember-bootstrap-datepicker#8]
Hi

Since the latest release, the datepicker has a sketchy behaviour. The problem appears only with European date format ('dd.mm.yyy').

When I click on (or enter manually) a date (e.g. "05.12.2015"),  the month and day switch on focus-out => "12.05.2015").
Using different formats, the problem could not be observed.

See this test:
```javascript
test('change input value', function(assert) {

  // normal date
  this.set('testDate','' );
  this.render(hbs`{{bootstrap-datepicker value=testDate format="dd.mm.yyyy" }}`);
  this.$('input').val('05.12.2015').trigger('focusout');
  assert.equal(this.get('testDate'), new Date('2015-12-05T00:00:00+0000'), 'converted javascript date');
  assert.equal(this.$('input').val(), '05.12.2015', 'typed date should stay');
});
```

outputs this:
![image](https://user-images.githubusercontent.com/1733057/34107967-758c86b0-e3fe-11e7-835e-bd968025bde9.png)

any ideas? could this come from not checking format for converting?:
https://github.com/topaxi/ember-bootstrap-datepicker/blob/196190662f5dccc9c1ac0f96a49fa298f6ceaad8/addon/components/bootstrap-datepicker.js#L51

**Comment by chvonrohr** [comment]
Is this add-on still maintained?

**Comment by topaxi** [comment]
Sorry I wasn't able to find time to review and fix things in this addon the last few weeks. I haven't been able to maintain this for a while now, I'd happily accept any PRs that fix this issue and don't break existing tests though.

I'd also happily add contributors to the addon if anyone is up for helping maintaining it.
